<?php

namespace App\Models;

use App\Traits\ManipulateBy;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Product extends Model
{
    use ManipulateBy;

    const ProductType=[
        'Simple'=>1,
        'Variation'=>2
    ];
    const ProductStatus=[
        'Active'=>1,
        'Inactive'=>2,
        'Pending'=>3,
        'Review'=>4,
        'Out of Stock'=>5,
    ];

    protected $table = 'products';

    protected $primaryKey = 'product_id';

    protected $fillable =[
        'category_id',
        'brand_id',
        'seller_id',
        'product_name',
        'product_sku',
        'product_slug',
        'thumb_id',
        'highlight',
        'description',
        'video_url',
        'product_type',
        'product_status',
        'created_by',
        'updated_by',
        'deleted_by',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'product_slug';
    }


    public function scopeNotDelete($query){
        return $query->where('product_status', '!=', config('app.delete'));
    }

    public function scopeIsActive($query){
        return $query->where('product_status', config('app.active'));
    }

    public function scopeInAdminReview($query){
        return $query->where('product_status', self::ProductStatus['Review']);
    }

    public function scopeIsOwner($query){
        return $query->where('seller_id', \auth()->user()->seller->seller_id);
    }

    public static function flipProductType()
    {
        return array_flip(self::ProductType);
    }

    public static function flipProductStatus()
    {
        return array_flip(self::ProductStatus);
    }


    public static function product_sku_generate(){
        $sku = '';
        for ($i=1; $i<=4; $i++){
            $sku.= Str::random(4);
            if($i != 4){
                $sku .= '-';
            }
        }

        return $sku;
    }



    public function scopeDateRangeWish($query,$request){

        if($request->date_range == 'today'){

            $today = Carbon::today()->format('Y-m-d');
            $query->whereDate('created_at', $today);
        }

        if($request->date_range == 'week'){
            $now = Carbon::now();
            $weekStartDate = $now->startOfWeek()->format('Y-m-d');
            $weekEndDate = $now->endOfWeek()->format('Y-m-d');
            $query->whereDate('created_at', '>=', $weekStartDate)->whereDate('created_at', $weekEndDate);
        }

        if($request->date_range == 'month'){
            $now = Carbon::now();
            $monthStartDate = $now->startOfMonth()->format('Y-m-d');
            $monthEndDate = $now->endOfMonth()->format('Y-m-d');
            $query->whereDate('created_at', '>=', $monthStartDate)->whereDate('created_at', $monthEndDate);

        }

        if($request->date_range == 'custom'){
            $query->whereDate('created_at', '>=', Carbon::parse($request->start_date)->format('Y-m-d'))
                ->whereDate('created_at','<=', Carbon::parse($request->end_date)->format('Y-m-d'));
        }

        return $query;
    }

    public function category(){
        return $this->belongsTo(Category::class, 'category_id', 'category_id');
    }

    public function brand(){
        return $this->belongsTo(Brand::class, 'brand_id', 'brand_id');
    }

    public function productDetails(){
        return $this->hasOne(ProductDetails::class, 'product_id', 'product_id');
    }

    public function variations(){
        return $this->hasMany(ProductVariation::class, 'product_id', 'product_id')->where('variation_status', config('app.active'));
    }

    public function productImages(){
        return $this->hasMany(ProductImage::class, 'product_id', 'product_id');
    }

    public function variation(){
        return $this->hasOne(ProductVariation::class, 'product_id', 'product_id');
    }

    public function thumbImage(){
        return $this->belongsTo(Attachment::class, 'thumb_id', 'attachment_id');
    }

    public function seller(){
        return $this->belongsTo(Seller::class, 'seller_id', 'seller_id');
    }

    public function orderItems(){
        return $this->hasMany(OrderItem::class, 'product_id', 'product_id');
    }

    public function reviews()
    {
        return $this->hasMany(Review::class, 'product_id', 'product_id');
    }

    public function tags()
    {
        return $this->hasMany(ProductTag::class, 'product_id', 'product_id')
            ->where('status', config('app.active'));
    }
}
